### ISSUE TITLE
currentParent.style.transform.length in Safari

### ISSUE THREAD

**Issue by SubVersive** [wwayne/react-tooltip#177]
Hello. Thank you very much for this nice component. We are using it in our application and it works pretty good.

Recently we found that it throw errors in different safari browsers, both on MacOS and IOS. Other browsers not affected.

This are an Error and StackTrace which we have.

TypeError: undefined is not an object (evaluating 'currentParent.style.transform.length')
  at target(app.js:59207:10)
  at currentEvent(app.js:58296:41)
  at updatePosition(app.js:58170:46)
  at setState(app.js:58094:19)
  at notifyAll(/checkin/scripts/vendor.js:3:17720)
  at close(/checkin/scripts/vendor.js:10:13669)
  at closeAll(/checkin/scripts/vendor.js:11:25554)
  at perform(/checkin/scripts/vendor.js:11:24741)
  at perform(/checkin/scripts/vendor.js:10:14153)
  at flushBatchedUpdates(/checkin/scripts/vendor.js:10:14475)
  at ? ([native code])
  at closeAll(/checkin/scripts/vendor.js:11:25554)
  at perform(/checkin/scripts/vendor.js:11:24741)
  at batchedUpdates(/checkin/scripts/vendor.js:8:3224)
  at enqueueUpdate(/checkin/scripts/vendor.js:10:12667)
  at enqueueUpdate(/checkin/scripts/vendor.js:10:2540)
  at enqueueCallback(/checkin/scripts/vendor.js:10:6269)
  at setState(/checkin/scripts/vendor.js:5:40470)
  at updateState(app.js:58089:17)
  at updateTooltip(app.js:58103:8)
  at updateTooltip([native code])

This line looks like cause an error

  var _ref = countTransform && getParent(target, countTransform) || { parentTop: 0, parentLeft: 0 };

The most reproducible environment is:
 Safari 6.X.X and Mac OS X 10.7.5.
We also have enough errors on Safari 8 and Mac Os 10.10

Version of react-tooltip: 3.1.2
Version of react: ^15.0.1

Thank you for your time and help.

**Comment by wwayne** [comment]
@SubVersive I've changed the way to calculate this value in latest version `3.1.5`, you can update to see if it is helps, related code in here: https://github.com/wwayne/react-tooltip/blob/master/src/utils/getPosition.js#L277

Meanwhile, if you don't have related html elements with the attribute`transform`, you can directly stop calculation this attribute by using `countTransform: false`

If all these don't help, I will take a further look.

**Comment by SubVersive** [comment]
Thank you very much for response. We will check and send back to you about the result.

**Comment by SubVersive** [comment]
Thank you for helping, for now it's working pretty stable. There is another issue with much lower number of occurrences I will be create separate issue for it.
