### ISSUE TITLE
npm start fails on devJS

### ISSUE THREAD

**Issue by stefanhayden** [wwayne/react-tooltip#307]
I've tried on ubuntu and osx with node 8 and 6. I get the below error and can not figure out what is wrong.

```
> react-tooltip@3.3.0 start /home/shayden/git/react-tooltip
> make dev

starting dev server...
make[1]: Entering directory '/home/shayden/git/react-tooltip'
Converting css...
css file has been transformed to JS successful
css file has been transformed successful
make[1]: Leaving directory '/home/shayden/git/react-tooltip'
[0] make[1]: Entering directory '/home/shayden/git/react-tooltip'
[1] make[1]: Entering directory '/home/shayden/git/react-tooltip'
[2] make[1]: Entering directory '/home/shayden/git/react-tooltip'
[2] Listening 8888...
[1] Rendering Complete, saving .css file...
[1] Wrote CSS to /home/shayden/git/react-tooltip/example/dist/index.css
[1] Rendering Complete, saving .css file...
[1] Wrote CSS to /home/shayden/git/react-tooltip/example/dist/style.css
[0] events.js:160
[0]       throw er; // Unhandled 'error' event
[0]       ^
[0] 
[0] Error: watch /home/shayden/git/react-tooltip/src/decorators/staticMethods.js ENOSPC
[0]     at exports._errnoException (util.js:1018:11)
[0]     at FSWatcher.start (fs.js:1443:19)
[0]     at Object.fs.watch (fs.js:1470:11)
[0]     at createFsWatchInstance (/home/shayden/git/react-tooltip/node_modules/chokidar/lib/nodefs-handler.js:37:15)
[0]     at setFsWatchListener (/home/shayden/git/react-tooltip/node_modules/chokidar/lib/nodefs-handler.js:80:15)
[0]     at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/shayden/git/react-tooltip/node_modules/chokidar/lib/nodefs-handler.js:228:14)
[0]     at FSWatcher.NodeFsHandler._handleFile (/home/shayden/git/react-tooltip/node_modules/chokidar/lib/nodefs-handler.js:255:21)
[0]     at FSWatcher.<anonymous> (/home/shayden/git/react-tooltip/node_modules/chokidar/lib/nodefs-handler.js:473:21)
[0]     at FSReqWrap.oncomplete (fs.js:123:15)
[0] Makefile:29: recipe for target 'devJS' failed
[0] make[1]: Leaving directory '/home/shayden/git/react-tooltip'
[0] make[1]: *** [devJS] Error 1
[0] make devJS exited with code 2
--> Sending SIGTERM to other processes..
```

**Comment by stefanhayden** [comment]
this worked on a mac with el capitan. not sure what the difference was. I'll close but would be nice if it worked in more environments.

**Comment by yelled3** [comment]
@stefanhayden I'm getting the same issue - did you find a solution?

**Comment by stefanhayden** [comment]
@yelled3 a newer version of OSX seem to fix whatever was wrong. It ended up working on el capitan on node 6. I didn't look in to why.
