### ISSUE TITLE
Upgrade from 3.6.1 to 3.8.1

### ISSUE THREAD

**Issue by danielrea** [wwayne/react-tooltip#442]
Hello,
I have recently updated from 3.6.1 to 3.8.1 and now I am getting this error:

```ERROR in ./node_modules/entities/maps/xml.json
Module parse failed: Unexpected token m in JSON at position 0 while parsing near 'module.exports = {"a...'
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token m in JSON at position 0 while parsing near 'module.exports = {"a...'
    at JSON.parse (<anonymous>)
    at parseJson (D:\Projects\project\node_modules\json-parse-better-errors\index.js:7:17)
    at JsonParser.parse (D:\Projects\project\node_modules\webpack\lib\JsonParser.js:16:16)
    at doBuild.err (D:\Projects\project\node_modules\webpack\lib\NormalModule.js:445:32)
    at runLoaders (D:\Projects\project\node_modules\webpack\lib\NormalModule.js:327:12)
    at D:\Projects\Articraft2\node_modules\loader-runner\lib\LoaderRunner.js:370:3
    at iterateNormalLoaders (D:\Projects\project\node_modules\loader-runner\lib\LoaderRunner.js:211:10)
    at iterateNormalLoaders (D:\Projects\project\node_modules\loader-runner\lib\LoaderRunner.js:218:10)
    at D:\Projects\Articraft2\node_modules\loader-runner\lib\LoaderRunner.js:233:3
    at runSyncOrAsync (D:\Projects\project\node_modules\loader-runner\lib\LoaderRunner.js:130:11)
 @ ./node_modules/htmlparser2/lib/Tokenizer.js 6:16-49
 @ ./node_modules/htmlparser2/lib/Parser.js
 @ ./node_modules/htmlparser2/lib/index.js
 @ ./node_modules/sanitize-html-react/index.js
 @ ./node_modules/react-tooltip/dist/index.js
 @ ./src/web/components/layout/Tooltip.js
 @ ./src/web/index.js
 @ multi (webpack)-dev-server/client?http://localhost:3001 (webpack)/hot/dev-server.js ./src/web/index
```

I haven't changed anything else including my json loader that I had before.

Thanks in advance for any help

**Comment by danielrea** [comment]
Had to use webpack default json loader and this worked.
