### ISSUE TITLE
Server side error - document is not defined 

### ISSUE THREAD

**Issue by bobiblazeski** [wwayne/react-tooltip#50]
Does server side rendering works ?

ReferenceError: document is not defined
      at ReactTooltip.render (/home/bobi/ws/node_modules/react-tooltip/dist/react-tooltip.js:365:10)
      at [object Object].ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext (/home/bobi/ws/node_modules/react/lib/ReactCompositeComponent.js:587:34)

**Comment by wwayne** [comment]
Just fix it by moving some code from `render` into `componentDidMount`.

**Comment by bobiblazeski** [comment]
I had to use state to  trigger tooltip rendering but it worked. Thank you.

**Comment by jacklj** [comment]
@bobiblazeski, did you mean something like this?
```jsx
        {this.state.displayTooltips && <ReactTooltip />}
```

Doesn't seem to work...
